{{- if and .Values.ssh.enabled (eq (include "access-gateway.accessMode" .) "ssh") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "access-gateway.fullname" . }}-ssh-config
  labels:
    {{- include "access-gateway.labels" . | nindent 4 }}
data:
  sshd_config: |
    {{- include "access-gateway.sshdConfig" . | nindent 4 }}
{{- end }}
