{{- if and .Values.externalSecrets.enabled .Values.mtls.enabled .Values.externalSecrets.mtls.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.mtls.secretName }}
  labels:
    {{- include "access-gateway.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.backendType }}
  target:
    name: {{ .Values.mtls.certSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.mtls.keys.ca }}
      remoteRef:
        key: {{ printf "%s/mtls/ca" .Values.externalSecrets.path }}
    - secretKey: {{ .Values.externalSecrets.mtls.keys.cert }}
      remoteRef:
        key: {{ printf "%s/mtls/cert" .Values.externalSecrets.path }}
    - secretKey: {{ .Values.externalSecrets.mtls.keys.key }}
      remoteRef:
        key: {{ printf "%s/mtls/key" .Values.externalSecrets.path }}
---
{{- end }}

{{- if and .Values.externalSecrets.enabled .Values.ssh.enabled .Values.externalSecrets.ssh.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.ssh.secretName | default (printf "%s-ssh" (include "access-gateway.fullname" .)) }}
  labels:
    {{- include "access-gateway.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.backendType }}
  target:
    name: {{ .Values.ssh.authorizedKeysSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecrets.ssh.key }}
      remoteRef:
        key: {{ printf "%s/ssh/authorized_keys" .Values.externalSecrets.path }}
{{- end }}

{{- if and .Values.externalSecrets.enabled .Values.twingate.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-twingate" (include "access-gateway.fullname" .) }}
  labels:
    {{- include "access-gateway.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.backendType }}
  target:
    name: {{ .Values.twingate.accessTokenSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.twingate.accessTokenKey }}
      remoteRef:
        key: {{ printf "%s/twingate/access_token" .Values.externalSecrets.path }}
    - secretKey: {{ .Values.twingate.refreshTokenKey }}
      remoteRef:
        key: {{ printf "%s/twingate/refresh_token" .Values.externalSecrets.path }}
---
{{- end }}