apiVersion: v1
kind: Service
metadata:
  name: {{ include "access-gateway.fullname" . }}
  labels:
    {{- include "access-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if and .Values.mtls.enabled (eq (include "access-gateway.accessMode" .) "mtls") }}
    - port: {{ .Values.mtls.proxy.port }}
      targetPort: mtls
      protocol: TCP
      name: mtls
    - port: {{ .Values.mtls.proxy.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
    {{- end }}
    {{- if and .Values.ssh.enabled (eq (include "access-gateway.accessMode" .) "ssh") }}
    - port: {{ .Values.ssh.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
    {{- end }}
    {{- if .Values.honeytrap.enabled }}
    {{- range .Values.honeytrap.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ default "TCP" .protocol }}
      name: {{ .name }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "access-gateway.selectorLabels" . | nindent 4 }}
