apiVersion: v1
kind: Service
metadata:
  name: {{ include "access-gateway.fullname" . }}
  labels:
    {{- include "access-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.mtls.enabled }}
    - port: {{ .Values.mtls.proxy.port }}
      targetPort: mtls
      protocol: TCP
      name: mtls
    - port: {{ .Values.mtls.proxy.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
    {{- end }}
    {{- if and .Values.ssh.enabled (not .Values.mtls.enabled) }}
    - port: {{ .Values.ssh.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
    {{- end }}
  selector:
    {{- include "access-gateway.selectorLabels" . | nindent 4 }}
